spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root1234
  application:
    name: order
  jpa:
    show-sql: true
env: test3
girl:
  name: aaa
  age: 22
