spring:
  datasource:
    url: jdbc:mysql://10.6.206.136:3306/springcloud?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root1234
  application:
    name: product
  jpa:
    show-sql: true
  redis:
    host: 10.6.206.136
    port: 6379
  rabbitmq:
    host: 10.6.206.136
    username: guest
    password: guest
    port: 5672
env: dev

