spring:
  datasource:
    url: jdbc:mysql://10.6.206.136:3306/springcloud?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root1234
  jpa:
    show-sql: true
  redis:
    host: 10.6.229.62
    port: 6379
